<?php

function custom_init() {
  switch ($_GET['q']) {
    case 'exame-oab':
      $result = views_get_view_result('exame_oab', 'page');
      if (isset($result[0])) {
        global $titleExame;
        $titleExame = $result[0]->node_title;
      }       
      break;
    
    case 'cursos-presenciais':
      $result = views_get_view_result('cursos_presenciais', 'page');
      $resultBanner = views_get_view_result('banner', 'block_2', 'cursos-presenciais');

      if (isset($result[0])) {
        global $cursoPresencialNid;
        $cursoPresencialNid = $result[0]->nid;
      }  

      if (isset($resultBanner[0])) {
        global $cursoPresencialBanner;
        $cursoPresencialBanner = $resultBanner[0]->field_field_image[0]['raw']['uri'];
      }       
      break;   
  } 
}

