<?php

function custom_init() {
  switch ($_GET['q']) {
    case 'exame-oab':
      $result = views_get_view_result('exame_oab', 'page');
      if (isset($result[0])) {
        global $titleExame;
        $titleExame = $result[0]->node_title;
      }       
      break;
    
    case 'cursos-online':
      $result = views_get_view_result('cursos_online', 'page');
      $resultBanner = views_get_view_result('banner', 'block_2', 'cursos-online');

      if (isset($result[0])) {
        global $cursoOnlineNid;
        $cursoOnlineNid = $result[0]->nid;
      }  

      if (isset($resultBanner[0])) {
        global $cursoOnlineBanner;
        $cursoOnlineBanner = $resultBanner[0]->field_field_image[0]['raw']['uri'];
      }       
      break;   
  } 
}

